definitions:
  test.Response:
    properties:
      code:
        type: integer
      data:
        type: object
      msg:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server Petstore server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Go-Starter-Gin API
  version: "1.0"
paths:
  /v1/test1:
    get:
      consumes:
      - application/json
      description: get apollo config
      produces:
      - application/json
      responses:
        "200":
          description: OK
          headers:
            Response:
              type: string
          schema:
            items:
              $ref: '#/definitions/test.Response'
            type: array
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Bad Request
          schema:
            type: string
      summary: List apollo some config
      tags:
      - Test API
swagger: "2.0"
